// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import {IVerifier} from "../../interfaces/IVerifier.sol";

/**
 * @title DepositVerifier
 * @author Sektorial12 (Cascade)
 * @notice Mock verifier for private deposits. In a real implementation, this would be auto-generated by circom.
 */
contract DepositVerifier is IVerifier {
    /**
     * @inheritdoc IVerifier
     */
    function verifyProof(bytes calldata, uint256[] calldata) external pure override returns (bool) {
        // This is a mock verifier and always returns true for testing purposes.
        return true;
    }
}
